let dataMovie = [
    {
      id: Math.random(),
      title: "Hitmen 2023",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRr9axMDDc3dyNqGND8lDs6hyfw9QeUFNX73_uIEwutAm1IfWPU5msKjAidC_SdC4E6bCU&usqp=CAU",
      rate: 5.1,
      decr: "Michael hero, a powerful CEO, seeks revenge for the murder of his grandson by offering a million-dollar reward for finding his killers, luring the world's top killers to the task at hand.",
      stream: "https://uqload.io/embed-clyxa4rgs0yz.html",
      lang: "EN",
      genre: "action",
      downlaod: "https://filelions.live/d/yfeamhvozrrf",
    },
    {
      id: Math.random(),
      title: "Darkland: The Return 2023",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQD1GLRscg83BkxsCfkGqrmHWS26TSmK_voffi1bR1qsz3_-GJBXMlUQO69xju5nothN50&usqp=CAU",
      rate: 6.5,
      decr: "Zaid is doing time in prison, but gets a chance to get out and see his son if he assists the police.",
      stream: "https://embedwish.com/e//310yqd3cgww6",
      lang: "EN",
      genre: "action",
      downlaod: "https://filelions.live/d/bmy24iqvlhke",
    },
    {
      id: Math.random(),
      title: "Sons of Summer 2023",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFrONOdeAguZGX8swPIPqWSF_xEb6S08d1qDIu9s0e_jOYzASr-pWviZdCJAMG3oa4YWg&usqp=CAU",
      rate: 3.8,
      decr: "Four surfing sons plan a tribute 'surfari' to a small beach town for one of their fathers murdered three decades earlier. But some road trips are to die for",
      stream: "https://embedwish.com/e//ob322p31xusk",
      lang: "EN",
      genre: "action",
      downlaod: "https://filelions.live/d/hsm10edk3rxn",
    },
    {
      id: Math.random(),
      title: "Skin Trade 2014",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaec2l5zl6C2gW3qTE2Cw9PdlD2RX_uqq3Vn03MlDw01Z3fYyv8SZoqv41MUcNvJGGQWo&usqp=CAU",
      rate: 5.6,
      decr: "After his family is killed by a Serbian gangster with international interests, NYC detective Nick goes to S.E. Asia and teams up with a Thai detective to get revenge and destroy the syndicates human trafficking network.",
      stream: "https://fviplions.com/v/g73t362prpmp",
      lang: "EN",
      genre: "action",
      downlaod: "https://fileved.cam/d/8f73is07erhy.html",
    },
    {
      id: Math.random(),
      title: "Punisher: War Zone 2008",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYwZUyWlwrhdsoQkOHXhdf83XWCfssjNB50AkvMMnk54zKQFTPTCk_6gWbHjYqn32BvBs&usqp=CAU",
      rate: 5.9,
      decr: "Frank Castle, known as the Punisher, ruthlessly demolishes organized crime, but it starts an even bigger war.",
      stream: "https://fviplions.com/v/jomnfqzmv4um",
      lang: "EN",
      genre: "action",
      downlaod: "https://fileved.cam/d/hnpxloimmflx.html",
    },
    {
      id: Math.random(),
      title: "Honey, I Shrunk the Kids 1989",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnKtS_kSTQbw-JZlMiSc5gwPhdVIGsqDfeu55CRUF42KE97FnOtKTYyB0W_mW10Pt4U-w&usqp=CAU",
      rate: 6.4,
      decr: "The scientist father of a teenage girl and boy accidentally shrinks his and two other neighborhood teens to the size of insects. Now the teens must fight diminutive dangers as the father searches for them.",
      stream: "https://fviplions.com/v/nwy1j66mqnnp",
      lang: "EN",
      genre: "comedy",
      downlaod: "https://fileved.cam/d/0gf81ghtia66.html",
    },
    {
      id: Math.random(),
      title: "ruce Almighty 2003",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSy4ca-QA8x_MHWmzxbxirpLAutw_t6zMm37FFKDmlY-adsCn47mbSyiNkb16gq28zNsus&usqp=CAU",
      rate: 6.8,
      decr: "A whiny news reporter is given the chance to step into God's shoes.",
      stream: "https://filelions.online/v/pn6fne74w0uy",
      lang: "EN",
      genre: "comedy",
      downlaod: "https://filelions.online/d/pn6fne74w0uy",
    },
    {
      id: Math.random(),
      title: "She Came to Me 2023",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoKzyDP5E_8uraEjIJ75KkeKEnN5XEoM4vHbQFl6cQ0eQE8N4jJ5RclUbUKDybHfb4zgY&usqp=CAU",
      rate: 6.4,
      decr: "A composer who suffers writer's block rediscovers his passion after an adventurous one-night stand.",
      stream: "https://fviplions.com/v/mk7cbup0578k",
      lang: "EN",
      genre: "comedy",
      downlaod: "https://fileved.cam/d/vdcxvzrj5i7e.html",
    },
    {
      id: Math.random(),
      title: "اتنين للايجار",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7EiSQO7wleN9xvN3DHa9tDG7dvLpguybhk45nth9DYTf7qJFqqsRHHA4sH8ViRMz7wxE&usqp=CAU",
      rate: 3.5,
      decr: "في إطار كوميدي، يبحث العاطلان صفيحة وحمادة عن فرصة عمل مناسبة لكسب قوت يومهما، ويقرران عرض أنفسهم للإيجار على من يدفع لهما لتلبية مطالبه كوسيلة لكسب الرزق.",
      stream: "https://filelions.online/v/63e6bxz2v0hl",
      lang: "AR",
      genre: "comedy",
      downlaod: "https://filelions.online/d/63e6bxz2v0hl",
    },
    {
      id: Math.random(),
      title: "ابن الحاج احمد",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHxoKIvwz4dhx5175-B8zGvfHRM-hSuxqNew_wK0YwhQGAb930Cx7UrYteNqkhf7n22LQ&usqp=CAU",
      rate: 5,
      decr: "يتورط شاب يدعى (أحمد) يعمل بائعًا بمتجر بقالة والده في متاعب جمة، بعدما يجد نفسه في مواجهة إحدى العصابات الخطيرة، مما يحتم عليه التعاون مع الشابة (نبيلة) والتصدي للخطر معًا.",
      stream: "https://fviplions.com/v/1gi7av7fdhzm",
      lang: "AR",
      genre: "comedy",
      downlaod: "https://fileved.cam/d/bbeb8bdd6jz7.html",
    },
    {
      id: Math.random(),
      title: "العميل صفر",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCNMOVxqBJkKaQkvXpCi77xKAmR4o-vOGAvdIgnH4mTkZAGXZxobSZg9AIv68jtjYIEIM&usqp=CAU",
      rate: 5.2,
      decr: "تدور أحداث الفيلم في إطار كوميدي حول فرد أمن يحلم أن يكون بطلاً مثل جيمس بوند؛ لكنه يفشل في ذلك ويتعرض للعديد من المواقف الكوميدية.",
      stream: "https://filelions.online/v/vfcfxn9brwrg",
      lang: "AR",
      genre: "comedy",
      downlaod: "https://filelions.online/v/vfcfxn9brwrg",
    },
    {
      id: Math.random(),
      title: "البعبع",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQn7rDxadKDInX7LhN9XM9Z-UtZC5cgxWjWvOxQ5eoQR_5pzAvp4EU5ADcsSqMKpe883BE&usqp=CAU",
      rate: 4,
      decr: "تدور أحداث الفيلم في يوم واحد حول سلطان، وهو مجرم مخضرم تم الإفراج عنه من السجن، ليقوم بعدها بعملية تسليم آثار لصالح أحد التجار، لكنه يغدر بهم ويستولي على الآثار والأموال ويبلغ عنهم الشرطة، ويستعد للسفر خارج مصر، إلا أنه يفاجأ بظهور أبنائه الاثنان في منزلة القديم واللذان لم يكن يعلم عنهما شيء منذ ولادتهما، فيضطر الهروب بهما وسط هجوم إحدى العصابات عليه.",
      stream: "https://filelions.live/v/b1ynpmkuw35l",
      lang: "AR",
      genre: "action",
      downlaod: "https://filelions.live/d/b1ynpmkuw35l",
    },
    {
      id: Math.random(),
      title: "هارلي",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkNnug-bq0PpS4a5H6njDc_rgNU-yU7t2TOMJxjwZrwCxirvktz9kRk3tC1pcNqlUykzk&usqp=CAU",
      rate: 3.8,
      decr: "يعود هارلي مهندس الميكانيكا من الخليج مع عائلته لاستكمال دراسته بمصر، ويقوده ذكائه وسرعته إلى العمل مع إحدى العصابات، ويصبح العنصر الأبرز والأقرب إلى زعيم العصابة",
      stream: "https://streamwish.to/e//udmhalehqrsu",
      lang: "AR",
      genre: "action",
      downlaod: "https://streamwish.to/f//udmhalehqrsu",
    },
    {
      id: Math.random(),
      title: "كيرة والجن",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThgc7PQMUO-bK5i4q_-w1VB6m6uyCKXYd4QN7U6QExWqov9LY7NHcQcAROW6v4uo2_kvY&usqp=CAU",
      rate: 7.9,
      decr: "يرصد الفيلم حالة الغليان التي كانت يموج بها الشارع المصري بالتزامن مع اندلاع ثورة 1919، وهو الحدث الكبير الذي يوحد مصائر أحمد عبدالحي كيرة وعبدالقادر الجن ليشتركا في النضال ضد المحتل اﻹنجليزي",
      stream: "https://filelions.to/v/2j084znm7qsw",
      lang: "AR",
      genre: "action",
      downlaod: "https://filelions.to/d/2j084znm7qsw",
    },
    {
      id: Math.random(),
      title: "الهيبة",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWCwt6t34Y92WCZ01IWiw3P3d_q-ySkQ6uSPg3XULbtDlsU-aZW94KODxiLKj913fl7cY&usqp=CAU",
      rate: 5.3,
      decr: "يكتشف جبل ان عدوه القديم والمسؤول عن اغتيال والده وظهور داعش بالهيبة، ناظم العالي والملقب بالختيار، ما زال على قيد الحياة. يقرر جبل ورجاله السفر الى اسطنبول وبلغاريا لاجل تصفية الحساب القديم",
      stream: "https://uqload.com/embed-b2w4ta0t8p5c.html",
      lang: "AR",
      genre: "action",
      downlaod: "https://uptobox.com/k1b9q0n4co9q",
    },
  ]; 

  export default dataMovie